### PR TITLE
Fixes #115

### LINKED ISSUE #115: Timing out results in confusing error and duplicated `:complete` callback
If one runs this code block…
```
(request
 "https://google.com"
 :parser 'json-read  ;; dummy
 :timeout 0.01  ;; intentionally timing out
 :complete (function* (lambda (&rest _) (message "Timed out."))))
```
…this is the result:
```
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to https://google.com.
Timed out.
REQUEST [error] Error (timeout) while connecting to https://google.com.
Timed out.
```

Two questions:
- What is the meaning of the first error message? 
- Why does the `:complete` function apparently run twice?

### PR DESCRIPTION
**Pull request by dickmao**
Under curl backend, the `request--curl-callback` will take care of
calling `request--callback`, and `request-response--timeout-callback`
should not do it again!

### CODE REVIEW

**Comment by matthew-piziak** [comment]
Thank you!

**Comment by titaniumbones** [comment]
I'm sorry I've been misisng in action -- @dickmao I don't have time to test this right away but if you feel ocnfident I will at lest merge to development, and hten prepare, ifnally ,to make that release we talked about in December (!!). If you have time to add some "Recent Updates" lines ot hte README that would be great, other wise I will make en effort to do those minor doc changes early next week.

**Comment by matthew-piziak** [comment]
Any way I can help here?

**Comment by matthew-piziak** [comment]
Looking forward to this. :) This will fix my mode line spam.

**Comment by matthew-piziak** [comment]
Any updates here? This keeps spamming my messages buffer. Any way I can help?

**Comment by matthew-piziak** [comment]
I've started using this branch directly with the following `straight.el` recipe:
```
(use-package request
  :straight (request :type git :host github :repo "dickmao/emacs-request" :branch "development"))
```

**Pull request merged**
