### PR TITLE
Fixed parameter ordering in assoc-string calls

### PR DESCRIPTION
**Pull request by abingham**

### CODE REVIEW

**Comment by abingham** [comment]
@tkf Are you there? This is a serious defect and really needs to be fixed.

**Comment by abingham** [comment]
Poke. Is there any chance of ever getting this merged in?

**Comment by shackra** [comment]
why is this not merged yet?

**Comment by abingham** [comment]
@tkf seems to have abandoned this project. I've looked into forking it, and the main issue there is [convincing the melpa maintainers to accept a new canonical source for the project](https://github.com/milkypostman/melpa/issues/1994).

But this bug bit me again recently, so I'll see if I can work with them on this.

**Comment by abingham** [comment]
I've sent an email to @tkf (using an address from a commit log, so I hope it's correct). If he doesn't respond to that fairly soon, we can try to convince MELPA to use a fork.

**Comment by shackra** [comment]
That would be great. Thought it worries me that @tfk is not answering, it would sucks if he was hit by a bus :/

El 25 de diciembre de 2015 02:47:53 CST, abingham <notifications@github.com> escribió:
>I've sent an email to @tkf (using an address from a commit log, so I
>hope it's correct). If he doesn't respond to that fairly soon, we can
>try to convince MELPA to use a fork.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tkf/emacs-request/pull/15#issuecomment-167210951

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by abingham** [comment]
He's made commits to github as recently as Aug. 30, so it would seem that
he's still around. Just not working on this project. But yes, he would be a
great loss.

**Comment by shackra** [comment]
@abingham I saw your pull requests merged on milkypostman/melpa#3461 it means we are good to go and install emacs-traad?

**Comment by abingham** [comment]
@shackra Yes, melpa is now updated with a patched request.el, so in principle everything should be good for traad. Let me know if you have any problems.

**Comment by shackra** [comment]
I'll let you know if I ever encounter one, thank you very much!

El lunes 04 de enero del 2016 a las 0149 horas, abingham escribió:

> @shackra Yes, melpa is now updated with a patched request.el, so in principle everything should be good for traad. Let me know if you have any problems.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tkf/emacs-request/pull/15#issuecomment-168604681


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by abingham** [comment]
Is this project going to be actively maintained now?

**Comment by syohex** [comment]
I got commit permission of this repository and I try to maintain as possible.

**Comment by abingham** [comment]
A while ago we switched the MELPA URL for this project to [my fork](https://github.com/abingham/emacs-request). If you're going to maintain this project, then you should see about getting MELPA switched back to this repository. I don't really want to maintain the project, but it was the only option after @tkf stopped paying attention.

**Comment by shackra** [comment]
Good Lord! Thank you!! 


Enviado desde mi dispositivo Samsung

-------- Mensaje original --------
De: Syohei YOSHIDA <notifications@github.com> 
Fecha: 17/04/2016  8:09  (GMT-06:00) 
Para: tkf/emacs-request <emacs-request@noreply.github.com> 
Cc: Jorge Araya Navarro <shackra@riseup.net> 
Asunto: Re: [tkf/emacs-request] Fixed parameter ordering in assoc-string
  calls (#15) 

I got commit permission of this repository and I try to maintain as possible.

**Pull request closed without merging**
