### PR TITLE
Support Unix socket for curl backend

### PR DESCRIPTION
**Pull request by syohex**
This is related to #35.
CC: @Silex

Sample code is here.
```lisp
(request
 "http:/hello.txt"
 :unix-socket "/tmp/app.sock"
 :parser (lambda () (buffer-string))
 :success (cl-function
	   (lambda (&key data &allow-other-keys)
	     (message "Got: %s" data))))
```

### CODE REVIEW

**Comment by Silex** [comment]
That looks nice! is it difficult to write a new backend? I might give a shot at writing one that uses `make-network-process` for a 100% elisp solution.

**Comment by syohex** [comment]
Why do you write new backend in pure elisp ?
Is it enough to use `curl` when using Unix domain socket ?

It is easy to install `curl` on Unix platform and faster than pure elisp code.

**Comment by Silex** [comment]
@syohex: pure elisp is more portable... but yeah requiring curl is not a big deal. I just like portable solutions and I think everyone would benefit from an alternative backend. So, is it complicated to write one or not?

I'll tell you how my tests about the curl backend goes.

**Comment by syohex** [comment]
> pure elisp is more portable... but yeah requiring curl is not a big deal. I just like portable solutions and I think everyone would benefit from an alternative backend.

I agree. However such new backend is almost same as `url-retrieve` backend except Unix domain socket. So I suppose there are few opportunities for using such backend. The best way is that `url-retrieve` supports Unix domain socket.

> So, is it complicated to write one or not?

Yes. And `make-network-process` is lower API so a lot of code is necessary for implementing as backend. (and a lot of code make maintenance difficult)

**Comment by Silex** [comment]
Alright, I guess this means I'll force curl on my users :wink:

Thanks for the feedback! I'll run some tests now.

**Comment by syohex** [comment]
Thanks for comments too.

**Comment by syohex** [comment]
I'll support unix domain socket for url-retrieve backend if url-retrive supports unix domain socket in the future.

**Comment by Silex** [comment]
:+1:

**Pull request merged**
